tables:
- schema: app
  name: accounts
  comment: アカウントマスタ
  columns:
  - name: id
    datatype: bigint(20) unsigned
    extra: auto_increment
    comment: primary key
  - name: email
    datatype: varchar(256)
    comment: メールアドレス
  - name: hashed_password
    datatype: varchar(256)
    comment: ハッシュ化済みパスワード
  - name: salt
    datatype: varchar(8)
    comment: ソルト
  - name: code
    datatype: varchar(64)
    comment: 表示ID
  - name: notification_id
    datatype: bigint(20) unsigned
    nullable: true
    comment: notifications.id
  - name: role
    datatype: tinyint(3) unsigned
    nullable: true
    comment: ロール
  - name: status
    datatype: tinyint(3) unsigned
    nullable: true
    comment: ステータス
  - name: flags
    datatype: int(10) unsigned
    nullable: true
    comment: フラグ
  - name: freezed_at
    datatype: timestamp
    nullable: true
    comment: 削除日
  - name: deleted_at
    datatype: timestamp
    nullable: true
    comment: 削除日
  - name: created_at
    datatype: timestamp
    default: CURRENT_TIMESTAMP
    nullable: true
    comment: 作成日
  - name: updated_at
    datatype: timestamp
    default: CURRENT_TIMESTAMP
    nullable: true
    comment: 更新日
  indexes:
  - name: PRIMARY
    unique: true
    columns:
    - id
  - name: accounts_email_IDX
    unique: true
    columns:
    - email
  - name: accounts_code_IDX
    unique: true
    columns:
    - code
  foreignkeys:
  - name: accounts_account_activates_FK
    column: id
    reftable: account_activates
    refcolumn: account_id
    hasone: false
    hasany: true
  enums:
  - column: role
    isstring: false
    values:
      ADMIN: 2
      MANAGER: 1
      USER: 0
  - column: status
    isstring: false
    values:
      ACTIVE: 1
      CREATED: 0
      DELETED: 9
      FREEZED: 8
  methods:
  - method: |-
      func (p *Account) Auth(db *gorm.DB, email string) bool {
        db.Where("Email = ? and status = ?", email, AccountStatusACTIVE).First(&p)
        return p.Email == email
      }
    imports: null
- schema: app
  name: pincodes
  comment: ピンコードマスタ
  columns:
  - name: id
    datatype: bigint(20) unsigned
    extra: auto_increment
    comment: primary key
  - name: pin
    datatype: varchar(6)
    comment: ピン
  - name: created_at
    datatype: timestamp
    default: CURRENT_TIMESTAMP
    nullable: true
    comment: 作成日
  - name: updated_at
    datatype: timestamp
    default: CURRENT_TIMESTAMP
    nullable: true
    comment: 更新日
  indexes:
  - name: PRIMARY
    unique: true
    columns:
    - id
  - name: pincodes_pin_IDX
    unique: true
    columns:
    - pin
  foreignkeys: []
  enums: []
  methods: []
- schema: app
  name: account_activates
  comment: UUID管理マスタ
  columns:
  - name: id
    datatype: bigint(20) unsigned
    extra: auto_increment
    comment: primary key
  - name: account_id
    datatype: bigint(20) unsigned
    comment: accounts.id
  - name: uuid
    datatype: varchar(64)
    comment: UUID
  - name: pincode_id
    datatype: bigint(20) unsigned
    comment: pincodes.id
  - name: expired_at
    datatype: timestamp
    nullable: true
    comment: PIN有効期限日時
  - name: activated_at
    datatype: timestamp
    nullable: true
    comment: アクティベート日時
  - name: last_login_at
    datatype: timestamp
    nullable: true
    comment: 最終ログイン日時
  - name: created_at
    datatype: timestamp
    default: CURRENT_TIMESTAMP
    nullable: true
    comment: 作成日
  - name: updated_at
    datatype: timestamp
    default: CURRENT_TIMESTAMP
    nullable: true
    comment: 更新日
  indexes:
  - name: PRIMARY
    unique: true
    columns:
    - id
  - name: account_activates_uuid_IDX
    unique: true
    columns:
    - uuid
  - name: account_activates_account_id_IDX
    unique: false
    columns:
    - account_id
  - name: account_activates_pincode_id_IDX
    unique: false
    columns:
    - pincode_id
  foreignkeys:
  - name: account_activates_accounts_FK
    column: account_id
    reftable: accounts
    refcolumn: id
    hasone: false
    hasany: false
  - name: account_activates_pincodes_FK
    column: pincode_id
    reftable: pincodes
    refcolumn: id
    hasone: false
    hasany: false
  enums: []
  methods:
  - method: "func (p *AccountActivate) Active(db *gorm.DB, uuid string) error {\n\treturn
      db.Joins(\"Account\").Where(\"uuid = ? and activated_at is not NULL and Account.status
      = ?\", uuid, AccountStatusACTIVE).First(&p).Error\n}"
    imports: null
- schema: app
  name: account_pincodes
  comment: アカウントとピンコードの紐付け
  columns:
  - name: id
    datatype: bigint(20) unsigned
    extra: auto_increment
    comment: primary key
  - name: account_id
    datatype: bigint(20) unsigned
    comment: accounts.id
  - name: pincode_id
    datatype: bigint(20) unsigned
    comment: pincodes.id
  - name: expired_at
    datatype: timestamp
    nullable: true
    comment: PIN有効期限日時
  - name: deleted_at
    datatype: timestamp
    nullable: true
    comment: 使用済み日時
  - name: created_at
    datatype: timestamp
    default: CURRENT_TIMESTAMP
    nullable: true
    comment: 作成日
  - name: updated_at
    datatype: timestamp
    default: CURRENT_TIMESTAMP
    nullable: true
    comment: 更新日
  indexes:
  - name: PRIMARY
    unique: true
    columns:
    - id
  - name: account_pincodes_account_id_IDX
    unique: true
    columns:
    - account_id
  - name: account_pincodes_pincode_id_IDX
    unique: true
    columns:
    - pincode_id
  foreignkeys:
  - name: account_pincodes_accounts_FK
    column: account_id
    reftable: accounts
    refcolumn: id
    hasone: false
    hasany: false
  - name: account_pincodes_pincodes_FK
    column: pincode_id
    reftable: pincodes
    refcolumn: id
    hasone: false
    hasany: false
  enums: []
  methods: []
- schema: app
  name: action_logs
  is_db: false
  comment: アクションログ ESIDX
  columns:
  - name: _id
    datatype: varchar(64)
    comment: ID
  - name: uuid
    datatype: varchar(64)
    comment: UUID
  - name: email
    datatype: varchar(256)
    nullable: true
    comment: メールアドレス
  - name: action_type
    datatype: int(3) unsigned
    nullable: true
    comment: タイプ
  - name: message
    datatype: text
    comment: メッセージ
  - name: recorded_at
    datatype: timestamp
    comment: 実行日時
  - name: created_at
    datatype: timestamp
    default: CURRENT_TIMESTAMP
    nullable: true
    comment: 作成日
  - name: updated_at
    datatype: timestamp
    default: CURRENT_TIMESTAMP
    nullable: true
    comment: 更新日
  indexes: []
  foreignkeys: []
  enums:
  - column: action_type
    isstring: false
    values:
      CLOUDMAIL: 15
      DETACHED: 4
      GAROON: 14
      INACTIVE: 2
      KINGOFTIME: 12
      KOTADMIN: 13
      PAUSED: 3
      RESUMED: 1
      SAVEYOU: 11
      SLACK: 16
  methods: []
