name: app
mode: 0
tables:
- schema: app
  name: accounts
  json_case: snake
  comment: アカウントマスタ
  columns:
  - name: id
    datatype: 0
    default: UUID()
    comment: ID
  - name: email
    datatype: 10
    count: 256
    comment: メールアドレス
  - name: hashed_password
    datatype: 10
    count: 256
    comment: ハッシュ化済みパスワード
  - name: salt
    datatype: 10
    count: 256
    comment: ソルト
  - name: notification_id
    datatype: 10
    count: 256
    comment: notifications.id
  - name: role
    datatype: 10
    count: 256
    comment: ロール
  - name: state
    datatype: 10
    count: 256
    comment: ステータス
  - name: flags
    datatype: 10
    count: 256
    comment: フラグ
  - name: freezed_at
    datatype: 10
    count: 256
    comment: 凍結日
  - name: deleted_at
    datatype: 10
    count: 256
    comment: 削除日
  - name: created_at
    datatype: 20
    default: current_timestamp()
    comment: 作成日
  - name: updated_at
    datatype: 20
    default: current_timestamp()
    nullable: true
    comment: 更新日
  indexes:
  - name: PRIMARY
    type: PRIMARY KEY
    columns:
    - id
  - name: accounts_email_IDX
    type: ""
    columns:
    - email
  - name: accounts_code_IDX
    type: ""
    columns:
    - email
  - name: accounts_multi_IDX
    type: UNIQUE
    columns:
    - email
    - deleted_at
  relations:
  - name: accounts_account_devices_FK
    column: id
    reftable: account_devices
    refcolumn: account_id
    hasone: false
    hasany: true
    isforeignkey: true
  enums:
  - column: role
    type: 2
    values:
    - key: Viewer
      value: 1
    - key: Writer
      value: 2
    - key: Manager
      value: 3
  - column: state
    type: 1
    values:
    - key: Created
      value: 1
    - key: Activated
      value: 2
    - key: Freezed
      value: 8
    - key: Deleted
      value: 9
  partitions: null
- schema: app
  name: pins
  json_case: snake
  comment: ピンコードマスタ
  columns:
  - name: id
    datatype: 0
    default: UUID()
    comment: ID
  - name: pin
    datatype: 10
    count: 128
    comment: ピン
  - name: usage
    datatype: 2
    comment: 用途
  - name: created_at
    datatype: 20
    default: current_timestamp()
    comment: 作成日
  - name: updated_at
    datatype: 20
    default: current_timestamp()
    nullable: true
    comment: 更新日
  indexes:
  - name: PRIMARY
    type: PRIMARY KEY
    columns:
    - id
  - name: pins_pin_IDX
    type: ""
    columns:
    - pin
  relations: []
  enums:
  - column: usage
    type: 1
    values:
    - key: Onetime
      value: 1
    - key: Pin
      value: 2
  partitions: null
- schema: app
  name: account_devices
  json_case: snake
  comment: デバイス管理マスタ
  columns:
  - name: id
    datatype: 0
    default: UUID()
    comment: ID
  - name: account_id
    datatype: 0
    comment: accounts.id
  - name: uuid
    datatype: 10
    count: 64
    comment: デバイスID
  - name: activated_at
    datatype: 20
    nullable: true
    comment: アクティベート日時
  - name: last_login_at
    datatype: 20
    nullable: true
    comment: 最終ログイン日時
  - name: created_at
    datatype: 20
    default: current_timestamp()
    comment: 作成日
  - name: updated_at
    datatype: 20
    default: current_timestamp()
    nullable: true
    comment: 更新日
  indexes:
  - name: PRIMARY
    type: PRIMARY KEY
    columns:
    - id
  - name: account_devices_uuid_IDX
    type: ""
    columns:
    - uuid
  - name: account_devices_account_id_IDX
    type: ""
    columns:
    - account_id
  - name: account_devices_pin_id_IDX
    type: ""
    columns:
    - pin_id
  relations:
  - name: account_devices_accounts_FK
    column: account_id
    reftable: accounts
    refcolumn: id
    hasone: false
    hasany: true
    isforeignkey: true
  - name: account_devices_pins_FK
    column: pin_id
    reftable: pins
    refcolumn: id
    hasone: false
    hasany: true
    isforeignkey: true
  enums: []
  partitions: null
- schema: app
  name: account_pins
  json_case: snake
  comment: アカウントとピンの紐付け
  columns:
  - name: id
    datatype: 0
    default: UUID()
    comment: ID
  - name: account_id
    datatype: 0
    comment: accounts.id
  - name: pin_id
    datatype: 0
    comment: pins.id
  - name: expired_at
    datatype: 20
    comment: PIN有効期限日時
  - name: deleted_at
    datatype: 20
    nullable: true
    comment: 使用済み日時
  - name: created_at
    datatype: 20
    default: current_timestamp()
    comment: 作成日
  - name: updated_at
    datatype: 20
    default: current_timestamp()
    nullable: true
    comment: 更新日
  indexes:
  - name: PRIMARY
    type: PRIMARY KEY
    columns:
    - id
  - name: account_pins_account_id_IDX
    type: ""
    columns:
    - account_id
  - name: account_pins_pin_id_IDX
    type: ""
    columns:
    - pin_id
  relations:
  - name: account_pins_accounts_FK
    column: account_id
    reftable: accounts
    refcolumn: id
    hasone: false
    hasany: true
    isforeignkey: true
  - name: account_pins_pins_FK
    column: pin_id
    reftable: pins
    refcolumn: id
    hasone: false
    hasany: true
    isforeignkey: true
  enums: []
  partitions: null
- schema: app
  name: action_logs
  json_case: snake
  comment: アクションログ
  columns:
  - name: id
    datatype: 0
    default: UUID()
    comment: ID
  - name: uuid
    datatype: 10
    count: 64
    comment: UUID
  - name: email
    datatype: 10
    count: 256
    comment: メールアドレス
  - name: action_type
    datatype: 1
    comment: タイプ
  - name: log
    datatype: 13
    comment: メッセージ
  - name: recorded_at
    datatype: 20
    comment: 実行日時
  - name: created_at
    datatype: 20
    default: current_timestamp()
    comment: 作成日
  - name: updated_at
    datatype: 20
    default: current_timestamp()
    nullable: true
    comment: 更新日
  indexes: []
  relations: []
  enums:
  - column: action_type
    type: 1
    values:
    - key: RESUMED
      value: 1
    - key: INACTIVE
      value: 2
    - key: PAUSED
      value: 3
    - key: DETACHED
      value: 4
    - key: SAVEYOU
      value: 11
    - key: KINGOFTIME
      value: 12
    - key: KOTADMIN
      value: 13
    - key: GAROON
      value: 14
    - key: CLOUDMAIL
      value: 15
    - key: SLACK
      value: 16
  partitions: null
- schema: app
  name: items
  json_case: snake
  comment: データバリエーション
  columns:
  - name: id
    datatype: 0
    default: UUID()
    comment: ID
  - name: price
    datatype: 10
    count: 32
    comment: 価格
  - name: created_at
    datatype: 20
    default: current_timestamp()
    comment: 作成日
  - name: updated_at
    datatype: 20
    default: current_timestamp()
    nullable: true
    comment: 更新日
  indexes:
  - name: PRIMARY
    type: PRIMARY KEY
    columns:
    - id
  - name: items_price_IDX
    type: ""
    columns:
    - price
  relations: []
  enums:
  - column: usage
    type: 1
    values:
    - key: Onetime
      value: 1
    - key: Pin
      value: 2
  partitions: null
