package mysql

const (
	GetSequences   = ""
	GetTables      = "SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = '%s'"
	GetIndexes     = "SELECT DISTINCT TABLE_SCHEMA, TABLE_NAME, INDEX_NAME, NON_UNIQUE FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = '%s' AND TABLE_NAME = '%s'"
	GetIndexColumn = "SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = '%s' AND TABLE_NAME = '%s' AND INDEX_NAME = '%s'"
	GetForeignkeys = `
		SELECT tc.TABLE_SCHEMA, tc.TABLE_NAME, tc.CONSTRAINT_NAME, kcu.COLUMN_NAME, kcu.REFERENCED_TABLE_NAME, kcu.REFERENCED_COLUMN_NAME 
			FROM INFORMATION_SCHEMA.table_constraints tc
			LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE kcu ON kcu.CONSTRAINT_NAME = tc.CONSTRAINT_NAME
			WHERE tc.TABLE_SCHEMA = '%s' AND tc.TABLE_NAME = '%s' AND tc.CONSTRAINT_TYPE = 'FOREIGN KEY';
	`
	GetCreateTable    = "SHOW CREATE TABLE %s"
	GetCreateDatabase = "CREATE DATABASE %s CHARACTER SET utf8mb4 COLLATE utf8mb4_bin"
	GetColumns        = "SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '%s' AND TABLE_NAME = '%s'"
)
